apiVersion: batch/v1
kind: Job
metadata:
  name: notify-post-job-failure
  annotations:
    argocd.argoproj.io/hook: SyncFail    # sync fail
spec:
  template:
    spec:
      containers:
        - name: notify-failure
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo 'MESSAGE FROM ARGOCD: The last sync is:  *** Sync Failed ***'"]
      restartPolicy: Never
  backoffLimit: 0
