apiVersion: batch/v1
kind: Job
metadata:
  name: notify-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync    # post sync
spec:
  template:
    spec:
      containers:
        - name: notify-success
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["echo 'MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***'"]
      restartPolicy: Never
  backoffLimit: 0
