apiVersion: batch/v1
kind: Job
metadata:
  name: health-check-pre-job
  annotations:
    # HOOK
    argocd.argoproj.io/hook: PreSync

    # HOOK DELETE POLICY
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
        - name: health-check
          image: busybox
          command: ["/bin/sh", "-c"]
          # flip exit 0 -> exit 1 to trigger the SyncFail hook instead of PostSync
          args: ["echo 'PreSync ran'; exit 0"]
      restartPolicy: Never
  backoffLimit: 0
